/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrainWaveRouteImport } from './routes/brain-wave'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as RunOfShowRouteImport } from './routes/run-of-show'
import { Route as TimelineRouteImport } from './routes/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainWaveRoute = BrainWaveRouteImport.update({
  id: '/brain-wave',
  path: '/brain-wave',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RunOfShowRoute = RunOfShowRouteImport.update({
  id: '/run-of-show',
  path: '/run-of-show',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brain-wave': typeof BrainWaveRoute
  '/calendar': typeof CalendarRoute
  '/overview': typeof OverviewRoute
  '/run-of-show': typeof RunOfShowRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brain-wave': typeof BrainWaveRoute
  '/calendar': typeof CalendarRoute
  '/overview': typeof OverviewRoute
  '/run-of-show': typeof RunOfShowRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brain-wave': typeof BrainWaveRoute
  '/calendar': typeof CalendarRoute
  '/overview': typeof OverviewRoute
  '/run-of-show': typeof RunOfShowRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brain-wave'
    | '/calendar'
    | '/overview'
    | '/run-of-show'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brain-wave'
    | '/calendar'
    | '/overview'
    | '/run-of-show'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/brain-wave'
    | '/calendar'
    | '/overview'
    | '/run-of-show'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrainWaveRoute: typeof BrainWaveRoute
  CalendarRoute: typeof CalendarRoute
  OverviewRoute: typeof OverviewRoute
  RunOfShowRoute: typeof RunOfShowRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain-wave': {
      id: '/brain-wave'
      path: '/brain-wave'
      fullPath: '/brain-wave'
      preLoaderRoute: typeof BrainWaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run-of-show': {
      id: '/run-of-show'
      path: '/run-of-show'
      fullPath: '/run-of-show'
      preLoaderRoute: typeof RunOfShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrainWaveRoute: BrainWaveRoute,
  CalendarRoute: CalendarRoute,
  OverviewRoute: OverviewRoute,
  RunOfShowRoute: RunOfShowRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
